spring:
    application:
      name: organization-service 
    profiles:
      active: dev
    config:
      import: configserver:http://localhost:8071
    main:
      allow-circular-references: true
